import { contextBridge, ipcRenderer } from 'electron'
import type { WalnutApi } from '../shared/contracts/app-state'

const walnutApi: WalnutApi = {
  loadAppState: () => ipcRenderer.invoke('app-state:load'),
  saveOnboardingProgress: (input) => ipcRenderer.invoke('app-state:save-onboarding-progress', input),
  completeOnboarding: (input) => ipcRenderer.invoke('app-state:complete-onboarding', input),
  startNewProfileSetup: () => ipcRenderer.invoke('app-state:start-new-profile-setup'),
  switchDeviceProfile: (profileId) => ipcRenderer.invoke('app-state:switch-device-profile', profileId),
  lockNow: (reason) => ipcRenderer.invoke('security:lock-now', reason),
  unlockWithPin: (pin) => ipcRenderer.invoke('security:unlock-with-pin', pin),
  beginRecoveryReset: (payload) => ipcRenderer.invoke('security:begin-recovery-reset', payload),
  saveAccountProfile: (draft) => ipcRenderer.invoke('app-state:save-account-profile', draft),
  copyRecoveryKeyAcknowledged: () => ipcRenderer.invoke('app-state:copy-recovery-ack'),
  downloadRecoveryKeyAcknowledged: () => ipcRenderer.invoke('app-state:download-recovery-ack'),
  getSecurityEvents: () => ipcRenderer.invoke('app-state:get-security-events'),
  stageImportFiles: (input) => ipcRenderer.invoke('import:stage-files', input),
  chooseImportSheet: (input) => ipcRenderer.invoke('import:choose-sheet', input),
  removeStagedFile: (input) => ipcRenderer.invoke('import:remove-staged-file', input),
  commitImportBatch: (input) => ipcRenderer.invoke('import:commit-batch', input),
  inspectPriorImportBatch: (priorBatchId) => ipcRenderer.invoke('import:inspect-prior-batch', priorBatchId),
  listImportHistory: (input) => ipcRenderer.invoke('import:list-history', input),
  getImportBatchDetail: (input) => ipcRenderer.invoke('import:get-batch-detail', input),
  getReviewQueue: (input) => ipcRenderer.invoke('import:get-review-queue', input),
  resolveReviewItems: (input) => ipcRenderer.invoke('import:resolve-review-items', input),
  restoreReviewItems: (input) => ipcRenderer.invoke('import:restore-review-items', input),
  listTransactions: (input) => ipcRenderer.invoke('transactions:list', input),
  getTransactionDetail: (input) => ipcRenderer.invoke('transactions:get-detail', input),
  updateTransaction: (input) => ipcRenderer.invoke('transactions:update', input),
  listCategories: () => ipcRenderer.invoke('categories:list'),
  createCategory: (input) => ipcRenderer.invoke('categories:create', input),
  updateCategory: (input) => ipcRenderer.invoke('categories:update', input),
  mergeCategory: (input) => ipcRenderer.invoke('categories:merge', input),
  deleteCategory: (input) => ipcRenderer.invoke('categories:delete', input),
  listRules: () => ipcRenderer.invoke('rules:list'),
  createRule: (input) => ipcRenderer.invoke('rules:create', input),
  updateRule: (input) => ipcRenderer.invoke('rules:update', input),
  toggleRule: (input) => ipcRenderer.invoke('rules:toggle', input),
  deleteRule: (input) => ipcRenderer.invoke('rules:delete', input),
  testRule: (input) => ipcRenderer.invoke('rules:test', input),
  previewRuleApplyToExisting: (input) => ipcRenderer.invoke('rules:preview-apply', input),
  applyRuleToExisting: (input) => ipcRenderer.invoke('rules:apply', input),
  getDashboardPreferences: () => ipcRenderer.invoke('dashboard:get-preferences'),
  setDashboardPreferences: (input) => ipcRenderer.invoke('dashboard:set-preferences', input),
  getDashboardSnapshot: (input) => ipcRenderer.invoke('dashboard:get-snapshot', input),
  getRecurringDetail: (input) => ipcRenderer.invoke('dashboard:get-recurring-detail', input),
  ping: () => ipcRenderer.invoke('app-state:ping')
}

contextBridge.exposeInMainWorld('walnut', walnutApi)
